# Generated by Django 5.1.6 on 2026-07-29 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vip_level',
            field=models.IntegerField(default=0),
        ),
    ]
