# Generated by Django 5.1.6 on 2025-04-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_cinemacluster_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
