# Generated by Django 5.1.6 on 2025-04-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_cinema_city_alter_room_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='number',
        ),
        migrations.AddField(
            model_name='seat',
            name='matrix_position',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seat',
            name='type',
            field=models.CharField(default='single', max_length=20),
        ),
    ]
