# Generated by Django 5.1.6 on 2025-04-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_remove_seat_number_seat_matrix_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='type',
        ),
        migrations.AddField(
            model_name='seat',
            name='column',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seat',
            name='row',
            field=models.IntegerField(default=0),
        ),
    ]
