# Generated by Django 5.1.6 on 2025-04-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_remove_seat_type_seat_column_seat_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='price',
            field=models.PositiveIntegerField(default=70000),
        ),
    ]
