# Generated by Django 5.1.6 on 2025-05-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_seat_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='seat_count',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='matrix_position',
        ),
        migrations.AlterField(
            model_name='seat',
            name='row',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
