# Generated by Django 5.1.6 on 2025-04-26 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinema', '0004_remove_seat_number_seat_matrix_position_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Snack',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='snacks/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('momo_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('momo_trans_id', models.CharField(blank=True, max_length=100, null=True)),
                ('momo_signature', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='payment.payment')),
                ('seat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinema.seat')),
                ('showtime', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinema.showtime')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentSnack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snacks', to='payment.payment')),
                ('snack', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.snack')),
            ],
        ),
    ]
