# Generated by Django 5.1.6 on 2025-05-11 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0007_remove_room_seat_count_remove_seat_matrix_position_and_more'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentSeat',
            new_name='Ticket',
        ),
    ]
