# Generated by Django 5.1.6 on 2025-05-28 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_paymentseat_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='momo_order_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='momo_signature',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='momo_trans_id',
        ),
    ]
